dsn: "root:my123456@tcp(127.0.0.1:3306)/mycube2?charset=utf8&parseTime=True&loc=Local"
QQBot:
  - group: true # 开启群模式
    groupList: [ # 开启
      "xxxx", "xxxx",
    ]
    enable: true
    appID: xxx
    token: xxx
  - group: false
    enable: true
    appID: xxx
    token: xxx
    groupList: [] # 为空不处理