dsn: "root:my123456@tcp(127.0.0.1:3306)/mycube2?charset=utf8&parseTime=True&loc=Local"

QQBot:
  # 魔缘的频道（无群）
  - group: false
    enable: true
    appID: 102076414
    token: g86R6ZNuJeThNqT9irBM1wTGi7sSKu5f
    groupList: [] # 为空不处理
  # 黄麻麻的机器人
  - group: true
    enable: true
    appID: 101986244
    token: 1sou4Anz0TyJ7kGLa1k2fKAl57B3tBxH
    groupList: ["DD7B07D6925232608C5F23AD76C12B41"] # 为空不处理